### ISSUE TITLE
[Subscriptions] Add View Button under Actions Column

### ISSUE THREAD

**Issue by xyberpastoril** [justinmanigo/HMEZGEB#170]
- Please make View Button under Actions Column – To View more information about the sign-up clients like e-mail address, number and soon.

**Comment by justinmanigo** [comment]
@xyberpastoril is this the exact page?
![image](https://user-images.githubusercontent.com/37109299/196614306-fe35f636-a184-415a-939b-cba6bdadf87e.png)

**Comment by justinmanigo** [comment]
#260
