### ISSUE TITLE
[Subscriptions] Make a search box that works for any data (e.g. `tin_number`, `mobile_number`)

### ISSUE THREAD

**Issue by xyberpastoril** [justinmanigo/HMEZGEB#174]
Please make a General Search box (search should work by any data for example by TIN# or Mobile Number or Name and information.

**Comment by justinmanigo** [comment]
@xyberpastoril  I think it is better to use table framework like dataTAbles or Tabulator. What do you think?

**Comment by justinmanigo** [comment]
#263
