### ISSUE TITLE
[Journal Voucher] Add `Reference Number` Field

### ISSUE THREAD

**Issue by xyberpastoril** [justinmanigo/HMEZGEB#204]
![image](https://user-images.githubusercontent.com/32955000/192662855-6bfc4888-e355-4eee-bec9-5aa9bd8b689f.png)
Please add 1 text box next to date for Reference number.

**Comment by justinmanigo** [comment]
![image](https://user-images.githubusercontent.com/37109299/196613257-f2c2473b-e39f-4984-a248-c6446970aa8c.png)

**Comment by xyberpastoril** [comment]
> can u check if this is ok?

Should be fine for now.
